jianda/apps/course/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from .views import CourseListView, CourseDetailView, CourseVideoView, AddCommentView, AddPraiseView, AddFavView


urlpatterns = [
    url('^list/$', CourseListView.as_view(), name="course_list"),
    url('^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='course_detail'),
    url('^video/(?P<video_id>\d+)/$', CourseVideoView.as_view(), name='course_video'),
    url(r'^add_comment/$', AddCommentView.as_view(), name='add_comment'),
    url(r'^add_fav/$', AddFavView.as_view(), name='add_fav'),
    url(r'^add_praise/$', AddPraiseView.as_view(), name='add_praise')
]

jianda/extra_plugins/qiniudemo/qiniudemo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'qiniudemo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^video/', include('video.urls', namespace='video')),
)

jianda/jianda/urls.py
# -*- coding: utf-8 -*-
"""jianda URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from users.views import LoginView, RegisterView, ForgetPwdView
import xadmin
from django.views.static import serve
from jianda.settings import MEDIA_ROOT

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    # url(r'^xadmin/', include(xadmin.site.urls, namespace='xadmin')),
    url('^$', TemplateView.as_view(template_name="index.html"), name='index'),
    url('^login/$', LoginView.as_view(), name='login'),
    url('^register/$', RegisterView.as_view(), name='register'),
    # 验证码
    url(r'^captcha/', include('captcha.urls')),
    url(r'^forget/$', ForgetPwdView.as_view(), name='forget_pwd'),

    # 学习课程
    url(r'^course', include('course.urls', namespace='course')),


    #配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
]

jianda/apps/users/forms.py
# -*- coding: utf-8 -*-

from django import forms
from captcha.fields import CaptchaField

from .models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=5)


class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=5)
    captcha = CaptchaField(error_messages={'invalid': u'验证码错误！'})


class ForgetForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField(error_messages={'invalid': u'验证码错误！'})


class ModifyPwdForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=5)
    password2 = forms.CharField(required=True, min_length=5)


class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nick_name', 'gender', 'birday', 'address', 'mobile']

jianda/extra_apps/xadmin/views/base.py
import sys
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.utils.encoding import force_unicode, force_text
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_unicode, smart_unicode, smart_str
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, basestring) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_unicode(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        for r in remove:
            for k in p.keys():
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        for r in remove:
            for k in p.keys():
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

    def init_request(self, *args, **kwargs):
        pass

    def init_plugin(self, *args, **kwargs):
        plugins = []
        for p in self.base_plugins:
            p.request = self.request

jianda/templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head lang="zh-CN">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="renderer" content="webkit"/>
    <meta name="keywords" content=""/>
    <meta name="description" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="shortcut icon" href="{% static 'images/favicon.ico'%}" type="image/x-icon" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet">
    {% block custom_css %}{%endblock%}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/login.js' %}"></script>
    <script src="{% static 'js/jquery.form.min.js'%}"></script>
    {%block custom_script%}{%endblock%}
    <title>课程模版</title>
</head>

<body>

<nav role="navigation" class="navbar navbar-default" style="font-size:15px !important;">
    <div class="navbar-header" style="margin-right:5%;margin-left:5%;">
        <a href="#" class="navbar-brand">
            <img alt="移动应用开发中间件ExMobi" src="/images/logo-new.png" style="height:100%"/>
        </a>
    </div>
    <div class="collapse navbar-collapse" style="margin-right:5%">
        <ul class="nav navbar-nav" style="margin-right:5%">
            <li class="active">
                <a href="{% url 'index'%}">首页</a>
            </li>
            <li>
                <a href="{% url 'course:course_list'%}">课程</a>
            </li>
            <li>
                <a href="#">计划</a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="{% url 'login' %}">登录</a>
            </li>
            <li>
                <a href="{% url 'register'%}">注册</a>
            </li>
        </ul>
        <form role="search" class="navbar-form navbar-left">
            <div class="form-group">
                <input type="text" placeholder="搜索" class="form-control" style="">
            </div>
            <button class="btn btn-default" type="button">搜索</button>
        </form>
    </div>
    <div class="modal fade" id="sign-modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#signin-form" aria-controls="signin-form" role="tab" data-toggle="tab">登录</a>
                        </li>
                        <li role="presentation">
                            <a href="#signup-form" aria-controls="signup-form" role="tab" data-toggle="tab">注册</a>
                        </li>
                    </ul>
                </div>
                <div class="modal-body">
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="signin-form">

                        </div>

                        <div role="tabpanel" class="tab-pane" id="signup-form">
                            <form method="post" action="{% url 'register' %}">
                                <div class="rlf-group">
                                <input type="text" class="form-group ipt" name="username" placeholder="请输入登录邮箱/手机号">
                                <p data-error-hint="请输入正确的邮箱或手机号"></p>
                            </div>

                            <div class="rlf-group clearfix">
                                <input type="text" class="form-group ipt" name="password" placeholder="请输入密码">
                                <p data-error-hint="请输入6-16位号码,不能用空格"></p>
                            </div>

                            <div class="rlf-group form-group clearfix">
                                {{ register_form.captcha }}
                                <!--<input type="text" class="form-group ipt ipt-verify l" name="email" placeholder="请输入验证码">-->
                                <!--<a href="" class="verift-img-wrap js-verify-refresh">-->
                                    <!--<img src="" class="verify-img">-->
                                <!--</a>-->
                                <!--<p data-error-hint="请输入6-16位号码,不能用空格"></p>-->
                            </div>

                            <div class="rlf-group  clearfix">
                                <input type="submit" value="注册" class="btn-red btn-full">
                            </div>
                            {% csrf_token %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>
{% block custom_content %}{% endblock %}

</body>

jianda/templates/course-detail.html
{%extends 'base.html'%}
{% load staticfiles %}
<!--css 文件-->
{%block custom_css%}
 <link href="{% static 'css/course.css' %}" rel="stylesheet">
{%endblock%}

<!--js文件-->
{%block custom_js%}
{%endblock%}

{%block custom_content%}

<div class="background-gradient">
    <div class="container">
        <div class="row">
            <ol class="breadcrumb">
                <li><a href="#">课程</a></li>
                <li><a href="#">后端开发</a></li>
                <li><a href="#">C++</a></li>
                <li><a href="#">C++远征之模版篇</a></li>
            </ol>
        </div>
        <div class="row padding ">
            <h4>{{course.name}}</h4>
        </div>
        <div class="row row-nav-margin">
            <div class="col-xs-4 col-md-2 edit">
                <h6>{{course.degree}}</h6>
                <span class="span-title">难度</span>
            </div>
            <div class="col-xs-4 col-md-2 edit">
                <h6>{{course.students}}</h6>
                <span class="span-title">学习人数</span>
            </div>
            <div class="col-xs-4 col-md-2 edit">
                <h6>{{course.learn_times}}</h6>
                <span class="span-title">时长</span>
            </div>
            <div class="col-xs-12 col-md-6">
                {%if has_learn %}
                    <a href="#" class="pull-right button-self">继续学习</a>
                {%else%}
                    <a href="?first_learn=true" class="pull-right button-self">开始学习</a>
                {%endif%}
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-9" style=";padding-right:15px;">
           <div class="mod-tab-menu">
               <ul class="course-menu clearfix nav " role="tablist">
                   <li role="presentation" class="active">
                       <a href="#tab-chapter" class="ui-tabs-active" role="tab" data-toggle="tab">
                           <span>章节</span>
                       </a>
                   </li>
                   <li role="presentation">
                       <a href="#tab-comment" class="ui-tabs-active" role="tab" data-toggle="tab">
                           <span>评论</span>
                       </a>
                   </li>
                   <li role="presentation">
                       <a href="#tab-question" class="ui-tabs-active" role="tab" data-toggle="tab">
                           <span>问答</span>
                       </a>
                   </li>
               </ul>
           </div>

            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="tab-chapter">
                    <div class="mod-chapters">
                        {% for lesson in course.get_course_lesson%}
                            <div class="chapter-title"  data-toggle="collapse" data-target="#js-chapter-videos_02">
                                <span>第{{forloop.counter}}章 {{lesson.name}}</span>
                                <i class="fa fa-caret-down pull-right icon-dropdown" aria-hidden="true"></i>
                            </div>
                            {% if has_learn %}
                                <div class="chapter chapter_active">
                                <div class="chapter-videos" id="js-chapter-videos_02">
                                <ul>
                                    {% for video in lesson.get_lesson_video %}
                                    <li>
                                        <a href="{% url 'course:course_video' video.id %}">
                                            <i class="fa fa-play " aria-hidden="true"></i>
                                            <span>{{forloop.parentloop.counter}}-{{forloop.counter}} {{video.name}}</span>
                                        </a>
                                    </li>
                                    {%endfor%}
                                </ul>
                            </div>

                            </div>
                            {%else%}
                             <div class="chapter chapter_active">
                                <span>{{lesson.desc}}</span>
                             </div>
                            {%endif%}
                        {%endfor%}
                    </div>
                </div>

                <div role="tabpanel" class="tab-pane" id="tab-comment">
                    <div class="video-comment-list" style="border-top: 0;">
                        <ul>
                            <li class="comment">
                                <div class="comment-avator clearfix">
                                    <a href="">
                                        <img width="40" height="40" src="image/image2.png">
                                    </a>
                                </div>
                                <div class="comment-main">
                                    <div class="comment-nick clearfix">
                                        <a href="" class="l">黑林小杰</a>
                                        <a href="" class="r">
                                            <i class="fa fa-comments-o" aria-hidden="true"></i>
                                            <span>回复</span>
                                        </a>
                                    </div>
                                    <div class="comment-content">讲师的声音好萌啊  好喜欢</div>
                                    <div class="comment-btm clearfix">
                                        <span class="comment-time">时间: 2017-03-17</span>
                                        <a class="comment-praise">
                                            <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                                            <span>20</span>
                                        </a>
                                    </div>
                                </div>
                            </li>
                            <li class="comment">
                                <div class="comment-avator clearfix">
                                    <a href="">
                                        <img width="40" height="40" src="image/image2.png">
                                    </a>
                                </div>
                                <div class="comment-main">
                                    <div class="comment-nick clearfix">
                                        <a href="" class="l">黑林小杰</a>
                                        <a href="" class="r">
                                            <i class="fa fa-comments-o" aria-hidden="true"></i>
                                            <span>回复</span>
                                        </a>
                                    </div>
                                    <div class="comment-content">讲师的声音好萌啊  好喜欢</div>
                                    <div class="comment-btm clearfix">
                                        <span class="comment-time">时间: 2017-03-17</span>
                                        <a class="comment-praise">
                                            <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                                            <span>20</span>
                                        </a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>

                </div>

                <div role="tabpanel" class="tab-pane" id="tab-question">

                </div>

            </div>


        </div>
        </div>
    </div>

{%endblock%}

jianda/templates/find_password.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head lang="zh-CN">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="renderer" content="webkit"/>
    <meta name="keywords" content=""/>
    <meta name="description" content="">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet">
     <link href="{% static 'css/index.css'%}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>课程模版</title>
</head>

<body>

 <div class="container">
     <div class="form-box">
         <div class="box-head">
            <h2>找回密码</h2>
         </div>
         <div class="box-body">
             <form class="register-form" id="fpw-form" method="post">
                <ul>
                    <li>
                        <input class="register-email form-control" type="text" placeholder="输入邮箱">
                    </li>
                    <li>
                        <input class="register-vertify form-control" type="text" placeholder="输入验证码">
                        <img src="" class="pull-right">
                    </li>
                    <li class="clearfix">
                        <button class="btn btn-large">下一步</button>
                    </li>
                </ul>
             </form>
         </div>

     </div>

 </div>

</body>

jianda/templates/login.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
  <meta charset="UTF-8">
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <title>慕学在线网登录</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<div class="bg" id="dialogBg"></div>
<header>
  <div class="c-box fff-box">
    <div class="wp header-box">
      <p class="fl hd-tips">慕学在线网，在线学习平台！</p>
      <ul class="fr hd-bar">
        <li class="active"><a href="{% url 'login' %}">[登录]</a></li>
        <li><a href="{% url 'register' %}">[注册]</a></li>
      </ul>
    </div>
  </div>
</header>
<section>
  <div class="c-box bg-box">
    <div class="login-box clearfix">
      <div class="hd-login clearfix">
        <a class="index-logo" href="{% url 'index' %}"></a>
        <h1>用户登录</h1>
        <a class="index-font" href="{% url 'index' %}">回到首页</a>
      </div>
      <div class="fl slide">
        <div class="imgslide">
          <ul class="imgs">
            <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}"/></a></li>
          </ul>
        </div>
        <div class="unslider-arrow prev"></div>
        <div class="unslider-arrow next"></div>
      </div>
      <div class="fl form-box">
        <h2>帐号登录</h2>
        <form action="/login/" method="post" autocomplete="off">
          <input type='hidden' name='csrfmiddlewaretoken' value='mymQDzHWl2REXIfPMg2mJaLqDfaS1sD5'/>
          <div class="form-group marb20 {% if login_form.errors.username %} errorput {% endif %} ">
            <input name="username" id="username" type="text" placeholder="手机号/邮箱"/>
          </div>
          <div class="form-group marb8 ">
            <input name="password" id="password_l" type="password" placeholder="请输入您的密码"/>
          </div>
          <div class="error btns login-form-tips" id="jsLoginTips">
            {% for key, error in login_form.errors.items %}
              {{ error }}
            {% endfor %}
            {{ msg }}
          </div>
          <div class="auto-box marb38">

            <a class="fr" href="{% url 'forget_pwd' %}">忘记密码？</a>
          </div>
          <input class="btn btn-green" id="jsLoginBtn" type="submit" value="立即登录 > "/>
        {% csrf_token %}
        </form>
        <p class="form-p">没有慕学在线网帐号？<a href="register.html">[立即注册]</a></p>
      </div>
    </div>
  </div>
</section>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<!--<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>-->
<!--<script src="{% static 'js/login.js' %}" type="text/javascript"></script>-->
</body>
</html>